name: CI test
on:
  push:
  
jobs: 
  testjob:
    runs-on: ubuntu-latest

    steps:
      - name: Check context
        run: echo ${{ github.context }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: test1
        run: echo "test1"
      - name: test2
        run: echo "test2"
      - name: post action
        if: always()
        run: echo "post action"