name: CI test
on:
  push:
  
jobs: 
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Check context
        run: echo ${{ github.context }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: test1
        run: /bin/bash ./test.sh ${{ github.ref_name }} ${{github.run_id}} ${{ github.run_number }} ;
      - name: test2
        run: echo "test2"
      - name: post action success
        if: success()
        run: echo "post action sss"
      - name: post action failed
        if: failure()
        run: echo "post action ffff"

  testjob2:
    runs-on: ubuntu-latest
    steps:
      - name: Check context
        run: echo ${{ github.context }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: test1
        run: /bin/bash ./test.sh ${{ github.ref_name }} ${{github.run_id}} ${{ github.run_number }} ;
      - name: test2
        run: echo "test2"; exit 1

  testjob3:
    runs-on: ubuntu-latest
    steps:
      - name: Check context
        run: echo ${{ github.context }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: test1
        run: /bin/bash ./test.sh ${{ github.ref_name }} ${{github.run_id}} ${{ github.run_number }} ;

  testjob98:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: TTTTTT
        run: echo ">>>>>>>>________<<<<<<<<<<<"

  testjob99:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: TTTTTT
        run: echo ">>>>>>>>________<<<<<<<<<<<"
    
